spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kmrpiyush95@gmail.com
    password: yeui kytd sybn suyi
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
    properties:
      domain_name: kmrpiyush95@gmail.com
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital

    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081

report:
  dir: C:\\Users\\kmrpi\\Desktop\\report